### ISSUE TITLE
Could not use FileTypeDetection

### ISSUE THREAD

**Issue by Vinnietram** [filetrust/product-file-type-detection#2]
Dear sir,

I recently ordered FileTypeDetection from your store and was provided a key,

File Type Detection - 1k files: C9AB-D458-8341-46A5

However, followed the link in the email I wasn't able to utilise it (got a 400 bad request),

Thanks,

**Comment by gw-sbirch** [comment]
@Vinnietram 

This has now been fixed on new orders. If you want a new key please contact me at sbirch@glasswallsolutions.com
